# Global Traefik configuration
api:
  dashboard: true

log:
  level: DEBUG

# Entrypoints configuration (HTTP and HTTPS)
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  qarth_local:
    address: ":8081"
  facturepro_local:
    address: ":8082"
  sf_api_local:
    address: ":8083"
  pwa_dashboard_local:
    address: ":5173"

# Let's Encrypt configuration for automatic SSL/TLS certificate management
certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme.json

      httpChallenge:
        entryPoint: http

# Docker provider configuration to detect containers dynamically
providers:
  docker:
    exposedByDefault: false

# Enable Traefik's dashboard (optional)
# You can access the dashboard at http://<your-server-ip>:8080
dashboard:
  entryPoint: http
